image: google/cloud-sdk #Python

before_script:
  - echo $GCLOUD_SERVICE_KEY > $HOME/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
  - gcloud config set project sas-engenharia-analytics
  # Environment Config
  - echo "" > $HOME/.env.yaml
  - 'echo "SENDGRID_KEY: \"$SENDGRID_KEY\"" >> $HOME/.env.yaml'

deploy:
  stage: deploy
  only:
    - master
  script:
    - rm -rf *.code-workspace .gitlab-ci.yml .editorconfig .eslintignore .eslintrc .mocharc
    - gcloud functions deploy load_covid_data --env-vars-file=.env.yaml --runtime=python38 --memory=1GB --region=us-central1 --timeout=540s --max-instances=3 --retry --trigger-resource gs://rep_einstein_kiyono/ --trigger-event google.storage.object.finalize --entry-point=load_covid_data

